kind: Deployment
apiVersion: apps/v1
metadata:
  name: pod1
spec:
  replicas: 2
  selector:
    matchLabels:
      myname: harpal
  template:
    metadata:
      labels:
        myname: harpal
    spec:
      containers:
      - name: con001
        image: nginx
