kind: ReplicationController
apiVersion: v1
metadata:
  name: myreplicationcontroler
spec:
  replicas: 2
  selector:
    myname: harpal
  template:
    metadata:
      labels:
        myname: harpal
    spec:
      containers:
      - name: coo012
        image: ubuntu
