kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: myreplicaset
spec:
  replicas: 2
  selector:
    matchExpressions:
      - key: myname
        operator: In
        values: 
          - sai
          - raj
          - akash
  template:
    metadata:
      labels:
        myname: sai
    spec:
      containers:
      - name: c003
        image: ubuntu


